modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL="https://github.com/JamCoreModding/utility-belt/issues"

[[mods]]
modId = "utility_belt"
version = "${file.jarVersion}"
displayName = "Utility Belt"
displayURL="https://github.com/JamCoreModding/utility-belt"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
Free your hotbar
'''

[[dependencies.utility_belt]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.utility_belt]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.utility_belt]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.utility_belt]]
modId = "jamlib"
mandatory = true
versionRange = "[${jamlib_version},)"
ordering = "AFTER"
side = "BOTH"
