[versions]
# https://modrinth.com/mod/architectury-api/versions
architectury = "11.1.17"

# https://projects.neoforged.net/neoforged/neoforge
neoforge = "20.4.198"

# https://fabricmc.net/develop
fabric-loader = "0.15.7"
fabric-api = "0.96.4+1.20.4"

# https://maven.jamalam.tech/#/releases
jamlib = "1.0.9+1.20.4"

# https://modrinth.com/mod/trinkets/versions
trinkets = "3.8.1"

# https://modrinth.com/mod/curios/versions
curios = "7.4.1+1.20.4"

# https://github.com/LlamaLad7/MixinExtras/releases
mixin-extras = "0.3.5"

# https://modrinth.com/mod/modmenu/versions
modmenu = "9.0.0"

[libraries]
architectury-common = { module = "dev.architectury:architectury", version.ref = "architectury" }
architectury-fabric = { module = "dev.architectury:architectury-fabric", version.ref = "architectury" }
architectury-neoforge = { module = "dev.architectury:architectury-neoforge", version.ref = "architectury" }

neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }

jamlib-common = { module = "io.github.jamalam360:jamlib", version.ref = "jamlib" }
jamlib-fabric = { module = "io.github.jamalam360:jamlib-fabric", version.ref = "jamlib" }
jamlib-neoforge = { module = "io.github.jamalam360:jamlib-neoforge", version.ref = "jamlib" }

trinkets = { module = "dev.emi:trinkets", version.ref = "trinkets" }

curios-neoforge = { module = "top.theillusivec4.curios:curios-neoforge", version.ref = "curios" }

mixin-extras-common = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixin-extras" }

modmenu = { module = "maven.modrinth:modmenu", version.ref = "modmenu" }
